import client from '@/app/libs/prismadb';
import { NextResponse } from 'next/server';

export async function GET(req) {
    const { searchParams } = new URL(req.url);
    // Get the page number, limit, and search query from the front end 
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '10');
    const searchQuery = searchParams.get('query') || ''; 

    // Calculate the number of user records to skip based on the page number and limit (this line of code was generated by Chat GPT) Prompt: How can i calculate the number of user records to skip based on the page number and limit
    const skip = (page - 1) * limit;

    try {
        // Fetch users with pagination and search functionality
        const usersWithFiles = await client.user.findMany({
            skip: skip,
            take: limit,
            where: {
                OR: [
                    { name: { contains: searchQuery, mode: 'insensitive' } }, 
                    { email: { contains: searchQuery, mode: 'insensitive' } },  
                ]
            },
            include: {
                files: true,  
            },
        });

        // Get the total count of users matching the search criteria
        const totalUsers = await client.user.count({
            where: {
                OR: [
                    { name: { contains: searchQuery, mode: 'insensitive' } },
                    { email: { contains: searchQuery, mode: 'insensitive' } },
                ]
            }
        });

        return NextResponse.json({
            status: 200,
            users: usersWithFiles,
            totalPages: Math.ceil(totalUsers / limit),
            currentPage: page,
        });
    } catch (error) {
        return NextResponse.json({
            status: 500,
            message: 'Error fetching users and files',
            error: error.message,
        });
    }
}